### ISSUE TITLE
Could not find the provider authority.

### ISSUE THREAD

**Issue by tajchert** [grandcentrix/tray#106]
I got this error from one of users phones:
```
Fatal Exception: java.lang.RuntimeException: Unable to create application XApplication.onCreate: net.grandcentrix.tray.core.TrayRuntimeException: Internal tray error. Could not find the provider authority. Please fill an issue at https://github.com/grandcentrix/tray/issues
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4824)
       at android.app.ActivityThread.access$1600(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by net.grandcentrix.tray.core.TrayRuntimeException: Internal tray error. Could not find the provider authority. Please fill an issue at https://github.com/grandcentrix/tray/issues
       at net.grandcentrix.tray.provider.TrayContract.getAuthority(SourceFile:138)
       at net.grandcentrix.tray.provider.TrayContract.generateContentUri(SourceFile:109)
       at net.grandcentrix.tray.provider.TrayContract.generateContentUri(SourceFile:80)
       at net.grandcentrix.tray.provider.TrayUri.(SourceFile)
       at net.grandcentrix.tray.provider.ContentProviderStorage.(SourceFile)
       at net.grandcentrix.tray.TrayPreferences.(SourceFile)
       at net.grandcentrix.tray.TrayPreferences.(SourceFile)
       at net.grandcentrix.tray.AppPreferences.(SourceFile)
       at X$Builder.(SourceFile)
       at X.init(SourceFile:36)
       at X.onCreate(SourceFile:57)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4821)
       at android.app.ActivityThread.access$1600(ActivityThread.java:157)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5551)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

**Comment by StefMa** [comment]
Hey,

can you please give us a little bit more infos?
How do you have setup Tray?
Have you noticed the [changes in 0.12.0](https://github.com/grandcentrix/tray/releases/tag/v0.12.0)? 
What call was made until it's crashed? 🤔

**Comment by tajchert** [comment]
Hi, sure.
We are soon about to open source our SDK so will will call you on that at that point (<1-2 weeks).
It was one time crash on over 20k devices so no any major issue at all.

Yes, we use 0.12.0 and no ContentProvider.

It was only "new AppPreferences(context)" from onCreate in Application.

**Comment by tajchert** [comment]
Ok, I checked Fabric once again:
6 users crashed with it, 6 times (all together so only once).
Samsung and LG.
Android 4.4.2, 6.0, 6.0.1, 4.1.2, 4.4.4

**Comment by fillobotto** [comment]
Same scenario for me. We are talking about lonely crashes but that's it

**Comment by eggcaker** [comment]
+1

**Comment by StefMa** [comment]
@fillobotto can you please show us some more information?
How do you setup tray? On which devices/OS will happen the crash? 🤔 

@tajchert is the SDK open source now? Would be great if we can have a look inside it...

**Comment by tajchert** [comment]
@StefMa - sorry not yet. I will post it here when done.

**Comment by OUCHUNYU** [comment]
I still have this problem. Any ideas?

**Comment by KB5201314** [comment]
I try to use Tray because I cant access the shared_prefs directory.
But I faced this Exception when i use tray,
So,I forgive it,

and now I find a mistake in my AndroidManifest.xml
``
            android:exported="false"
            android:isolatedProcess="true"  //here 
            android:label="@string/service_name"
            android:process=":autoupdate"
            android:permission="">
``
set `android:isolatedProcess="true"` makes my application process and the service process run in different UID (i check it by `ps` commend),
 and **that cause the Permission Denied in SharedPreference**.



I don't know if it is the same mistake that cause the tray to an Exception.
