### ISSUE TITLE
Caused by: net.grandcentrix.tray.core.TrayRuntimeException: 

### ISSUE THREAD

**Issue by leafmi** [grandcentrix/tray#110]
Caused by: net.grandcentrix.tray.core.TrayRuntimeException: 
  at net.grandcentrix.tray.provider.TrayContract.getAuthority(TrayContract.java:138)
  at net.grandcentrix.tray.provider.TrayContract.generateContentUri(TrayContract.java:109)
  at net.grandcentrix.tray.provider.TrayContract.generateContentUri(TrayContract.java:80)
  at net.grandcentrix.tray.provider.TrayUri.<init>(TrayUri.java:75)
  at net.grandcentrix.tray.provider.ContentProviderStorage.<init>(ContentProviderStorage.java:146)
  at net.grandcentrix.tray.TrayPreferences.<init>(TrayPreferences.java:43)
  at net.grandcentrix.tray.TrayPreferences.<init>(TrayPreferences.java:48)
  at net.grandcentrix.tray.AppPreferences.<init>(AppPreferences.java:41)
  at com.lionmobi.netmaster.manager.SettingManager.<init>(SettingManager.java:33)
  at com.lionmobi.netmaster.manager.SettingManager.getSettingInstance(SettingManager.java:26)
  at com.lionmobi.netmaster.service.WifiRemoteService.onCreate(WifiRemoteService.java:574)
  at android.app.ActivityThread.handleCreateService(ActivityThread.java:2820)

**Comment by leafmi** [comment]
How to solve

**Comment by passsy** [comment]
We need additional information. Where are you calling tray? Which device-, os-version?
