### ISSUE TITLE
net.grandcentrix.tray.core.TrayRuntimeException: Internal tray error. Could not find the provider authority.

### ISSUE THREAD

**Issue by ShengYanMei** [grandcentrix/tray#117]
[//]: # (We want to provide the best support with your issue. So please answer the following questions carefully)
[//]: # (You don't have an issue but a remark or a feature? Please remove this default template and just write your text 😉)

#### Android Version (E.g. Marshmallow or better API 23)
android 4.2 ~ 6.0 
#### Stacktrace
<details>
  <summary>Stacktrace</summary>
net.grandcentrix.tray.core.TrayRuntimeException: Internal tray error. Could not find the provider authority.
  ```
  <!-- Please put your stracktrace in here -->
 java.lang.RuntimeException: Unable to resume activity {****}: net.grandcentrix.tray.core.TrayRuntimeException: Internal tray error. Could not find the provider authority. Please fill an issue at https://github.com/grandcentrix/tray/issues
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2830)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2859)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2284)
	at android.app.ActivityThread.access$800(ActivityThread.java:142)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1213)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5241)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
	at dalvik.system.NativeStart.main(Native Method)
</details>

#### Description (Just a place with additional information, more == better)

**Comment by OUCHUNYU** [comment]
Same here

**Comment by g19980115** [comment]
+1

**Comment by g19980115** [comment]
Log supplement :
```

Caused by:

net.grandcentrix.tray.core.TrayRuntimeException:Internal tray error. Could not find the provider authority. Please fill an issue at https://github.com/grandcentrix/tray/issues
net.grandcentrix.tray.provider.TrayContract.getAuthority(TrayContract.java:138)
net.grandcentrix.tray.provider.TrayContract.generateContentUri(TrayContract.java:109)
net.grandcentrix.tray.provider.TrayContract.generateContentUri(TrayContract.java:80)
net.grandcentrix.tray.provider.TrayUri.<init>(TrayUri.java:75)
net.grandcentrix.tray.provider.ContentProviderStorage.<init>(ContentProviderStorage.java:146)
net.grandcentrix.tray.TrayPreferences.<init>(TrayPreferences.java:43)
net.grandcentrix.tray.TrayPreferences.<init>(TrayPreferences.java:48)

```
