### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lnet/grandcentrix/tray/R$string;

### ISSUE THREAD

**Issue by kennir** [grandcentrix/tray#138]
[//]: # (We want to provide the best support with your issue. So please answer the following questions carefully)
[//]: # (You don't have an issue but a remark or a feature? Please remove this default template and just write your text 😉)

#### How have you setup tray (E.g. Initialized in Application.onCreate, in an Activity, BroadcastReceiver, IntentService, MainThread)

Application.onCreate

#### Device(s) (E.g. Samsung Galaxy S8)

RedMi

#### Android Version (E.g. Marshmallow or better API 23)

API23

#### Stacktrace
<details>
  <summary>Stacktrace</summary>

  ```
03-05 15:55:05.045 15503-15503/com.knew.feed E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.knew.feed, PID: 15503
    java.lang.NoClassDefFoundError: Failed resolution of: Lnet/grandcentrix/tray/R$string;
        at net.grandcentrix.tray.provider.TrayContract.checkOldWayToSetAuthority(TrayContract.java:92)
        at net.grandcentrix.tray.provider.TrayContract.getAuthority(TrayContract.java:122)
        at net.grandcentrix.tray.provider.TrayContract.generateContentUri(TrayContract.java:109)
        at net.grandcentrix.tray.provider.TrayContract.generateContentUri(TrayContract.java:80)
        at net.grandcentrix.tray.provider.TrayUri.<init>(TrayUri.java:75)
        at net.grandcentrix.tray.provider.ContentProviderStorage.<init>(ContentProviderStorage.java:146)
        at net.grandcentrix.tray.TrayPreferences.<init>(TrayPreferences.java:43)
        at net.grandcentrix.tray.TrayPreferences.<init>(TrayPreferences.java:48)
        at com.knew.feed.component.MyAppPreferences.<init>(MyAppPreferences.kt:10)
        at com.knew.feed.App$prefs$2.invoke(App.kt:45)
        at com.knew.feed.App$prefs$2.invoke(App.kt:36)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.knew.feed.App.getPrefs(App.kt)
        at com.knew.feed.utils.DistributionChannelUtils$prefs$2.invoke(DistributionChannelUtils.kt:17)
        at com.knew.feed.utils.DistributionChannelUtils$prefs$2.invoke(DistributionChannelUtils.kt:14)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.knew.feed.utils.DistributionChannelUtils.getPrefs(DistributionChannelUtils.kt)
        at com.knew.feed.utils.DistributionChannelUtils.access$getPrefs$p(DistributionChannelUtils.kt:14)
        at com.knew.feed.utils.DistributionChannelUtils$distributionChannel$2.invoke(DistributionChannelUtils.kt:22)
        at com.knew.feed.utils.DistributionChannelUtils$distributionChannel$2.invoke(DistributionChannelUtils.kt:14)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.knew.feed.utils.DistributionChannelUtils.getDistributionChannel(DistributionChannelUtils.kt)
        at com.knew.feed.utils.DistributionChannelUtils.isDevelopment(DistributionChannelUtils.kt:29)
        at com.knew.feed.utils.LoggerUtilsKt.initLogger(LoggerUtils.kt:35)
        at com.knew.feed.App.init(App.kt:85)
        at com.knew.feed.App.onCreate(App.kt:57)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5019)
        at android.app.ActivityThread.access$1800(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5845)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "net.grandcentrix.tray.R$string" on path: DexPathList[[zip file "/data/app/com.knew.feed-1/base.apk"],nativeLibraryDirectories=[/data/app/com.knew.feed-1/lib/arm, /data/app/com.knew.feed-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at net.grandcentrix.tray.provider.TrayContract.checkOldWayToSetAuthority(TrayContract.java:92) 
        at net.grandcentrix.tray.provider.TrayContract.getAuthority(TrayContract.java:122) 
        at net.grandcentrix.tray.provider.TrayContract.generateContentUri(TrayContract.java:109) 
        at net.grandcentrix.tray.provider.TrayContract.generateContentUri(TrayContract.java:80) 
        at net.grandcentrix.tray.provider.TrayUri.<init>(TrayUri.java:75) 
        at net.grandcentrix.tray.provider.ContentProviderStorage.<init>(ContentProviderStorage.java:146) 
        at net.grandcentrix.tray.TrayPreferences.<init>(TrayPreferences.java:43) 
        at net.grandcentrix.tray.TrayPreferences.<init>(TrayPreferences.java:48) 
        at com.knew.feed.component.MyAppPreferences.<init>(MyAppPreferences.kt:10) 
        at com.knew.feed.App$prefs$2.invoke(App.kt:45) 
        at com.knew.feed.App$prefs$2.invoke(App.kt:36) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.knew.feed.App.getPrefs(App.kt) 
        at com.knew.feed.utils.DistributionChannelUtils$prefs$2.invoke(DistributionChannelUtils.kt:17) 
        at com.knew.feed.utils.DistributionChannelUtils$prefs$2.invoke(DistributionChannelUtils.kt:14) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.knew.feed.utils.DistributionChannelUtils.getPrefs(DistributionChannelUtils.kt) 
        at com.knew.feed.utils.DistributionChannelUtils.access$getPrefs$p(DistributionChannelUtils.kt:14) 
        at com.knew.feed.utils.DistributionChannelUtils$distributionChannel$2.invoke(DistributionChannelUtils.kt:22) 
        at com.knew.feed.utils.DistributionChannelUtils$distributionChannel$2.invoke(DistributionChannelUtils.kt:14) 
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) 
        at com.knew.feed.utils.DistributionChannelUtils.getDistributionChannel(DistributionChannelUtils.kt) 
        at com.knew.feed.utils.DistributionChannelUtils.isDevelopment(DistributionChannelUtils.kt:29) 
        at com.knew.feed.utils.LoggerUtilsKt.initLogger(LoggerUtils.kt:35) 
        at com.knew.feed.App.init(App.kt:85) 
        at com.knew.feed.App.onCreate(App.kt:57) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1018) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5019) 
        at android.app.ActivityThread.access$1800(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:5845) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:768) 
    	Suppressed: java.lang.ClassNotFoundException: net.grandcentrix.tray.R$string
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 37 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

  ```
</details>

**Comment by muyoumingzi** [comment]
the question occurred to me! I just updated my gradle version and  gradle plugin version ,the problem came . It seems that the library has been aborted?
