### ISSUE TITLE
android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database

### ISSUE THREAD

**Issue by luyuanwu** [grandcentrix/tray#59]
I have the same problem.

android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:743)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1606)
	at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1552)
	at net.grandcentrix.tray.provider.SqliteHelper.a(ProGuard:164)
	at net.grandcentrix.tray.provider.TrayContentProvider.insert(ProGuard:179)
	at android.content.ContentProvider$Transport.insert(ContentProvider.java:246)
	at android.content.ContentResolver.insert(ContentResolver.java:1256)
	at net.grandcentrix.tray.provider.TrayProviderHelper.a(ProGuard:128)
	at net.grandcentrix.tray.provider.ContentProviderStorage.a(ProGuard:227)
	at net.grandcentrix.tray.core.Preferences.b(ProGuard:123)
	at com.meituan.banma.util.SPUtil.b(ProGuard:52)
	at com.meituan.banma.model.AppPrefs.b(ProGuard:159)
	at com.meituan.banma.model.UserModel.a(ProGuard:102)
	at com.meituan.banma.model.UserModel$2.onResponse(ProGuard:85)
	at com.meituan.banma.net.request.BaseRequest.a(ProGuard:104)
	at com.meituan.banma.net.request.BaseRequest$1.onResponse(ProGuard:85)
	at com.meituan.banma.net.request.BaseRequest$1.onResponse(ProGuard:82)
	at com.meituan.banma.net.request.BaseRequest$InnerRequest.deliverResponse(ProGuard:212)
	at com.meituan.banma.net.request.BaseRequest$InnerRequest.deliverResponse(ProGuard:189)
	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ProGuard:99)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:230)
	at android.app.ActivityThread.main(ActivityThread.java:5682)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:998)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:793)

How to solve?
I'm using 1.0.0-rc2 version.

**Comment by passsy** [comment]
fixed in latest `0.11.0` release
