### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Query is not supported for Uri:

### ISSUE THREAD

**Issue by acnono** [grandcentrix/tray#64]
Caused by: java.lang.IllegalArgumentException: Query is not supported for Uri: content://com.sankuai.meituan.dispatch.crowdsource.tray/preferences/com.sankuai.meituan.xxxxx/xxxxxxxe.mark?backup=true
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:413)
	at android.content.ContentResolver.query(ContentResolver.java:461)
	at android.content.ContentResolver.query(ContentResolver.java:404)
	at net.grandcentrix.tray.provider.TrayProviderHelper.a(ProGuard:141)
	at net.grandcentrix.tray.provider.ContentProviderStorage.a(ProGuard:2172)
	at net.grandcentrix.tray.core.Preferences.a(ProGuard:68)
	at com.meituan.xxx.util.SPUtil.a(ProGuard:1118)
	at com.meituan.xxx.util.SPUtil.a(ProGuard:25)

**Comment by StefMa** [comment]
Can you please provide some code to reproduce this exception?

**Comment by passsy** [comment]
I ran in the same problem. This happens when you use `put("", "data")` with an empty key. Tray should provide a better error message in this case
