### ISSUE TITLE
Issue Registering Provider in Robolectric Tests

### ISSUE THREAD

**Issue by KioKrofovitch** [grandcentrix/tray#71]
I'm trying to run Robolectric tests with code that uses Tray, but immediately get the following error for any classes that access `AppPreferences`:

```java.lang.IllegalStateException: could not access stored data with uri content://com.example.tray/internal_preferences/com.example/version?backup=true. Is the provider registered in the manifest of your application?```

Is there a suggested set up for unit testing classes that use Tray? I tried following the existing Tray library unit tests, but ran into issues since `TrayContract` is private scope.

**Comment by passsy** [comment]
I never tested it with Robolectric but it doesn't look like a big problem.

You have to make sure that `context.getString(R.string.tray__authority)` ([here](https://github.com/grandcentrix/tray/blob/master/library/src/main/java/net/grandcentrix/tray/provider/TrayContract.java#L124) `context` is the Application context) returns the correct authority. I'm not sure if Robolectric works with the `generated.xml` files which could cause this error.

Please check if [mocking the string resource](http://stackoverflow.com/a/31697963/669294) works.

```java
RuntimeEnvironment.application = spy(RuntimeEnvironment.application);
when(RuntimeEnvironment.application.getApplicationContext())
    .thenReturn(RuntimeEnvironment.application);

Resources spiedResources = spy(app.getResources());
when(app.getResources())
    .thenReturn(spiedResources);

when(spiedResources.getString(R.string.tray__authority))
    .thenReturn("my.authority.for.tray");
```

**Comment by jannisveerkamp** [comment]
As @passsy mentioned I guess Robolectric doesn't find a generated String for the authority.

I'm not an Robolectric expert, but you can provide a BuildConfig for it. Make sure you register the correct Provider for Robolectric too. Here is an example (which hopefully works 😄 )

```
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class)
public class MyAwesomeTest {

    @Before
    public void setUp() throws Exception {
        TrayContentProvider provider = new TrayContentProvider();
        provider.onCreate();
        ShadowContentResolver.registerProvider(BuildConfig.APPLICATION_ID + ".preferences", provider);
    }

    @Test
    public void myTotallyAwesomeTest() throws Exception {
        AppPreferences appPreferences = new AppPreferences(RuntimeEnvironment.application);
        appPreferences.put("key", "test");
        String test = appPreferences.getString("key");
        assertThat(test, equalTo("test"));
    }
}
```

Let me know if this works.

**Comment by KioKrofovitch** [comment]
Thank you both so much for your help!  I have now successfully moved on from the URI error, but still get an error during `setUp` when I attempt to access `R.string.tray__authority`.  

```android.content.res.Resources$NotFoundException: unknown resource 2131034186```

I also get the same error if I skip the string resource mocking code and I attempt to run only the code suggested by @jannisveerkamp . I get the error when I call `provider.onCreate()` (which ultimately attempts to access `R.string.tray__authority`).

Its like Robolectric cannot even see this string resource at all.

```
@RunWith(RobolectricTestRunner.class)
@Config(constants = BuildConfig.class, sdk=21)
public class TrayTest {

  @Before
  public void setUp() throws Exception {
    RuntimeEnvironment.application = spy(RuntimeEnvironment.application);
    when(RuntimeEnvironment.application.getApplicationContext())
        .thenReturn(RuntimeEnvironment.application);

    Resources spiedResources = spy(RuntimeEnvironment.application.getResources());
    when(RuntimeEnvironment.application.getResources())
        .thenReturn(spiedResources);

    when(spiedResources.getString(R.string.tray__authority))
        .thenReturn("com.example.tray");

    TrayContentProvider provider = new TrayContentProvider();
    provider.onCreate();
    ShadowContentResolver.registerProvider(BuildConfig.APPLICATION_ID + ".preferences", provider);
  }

  @Test
  public void myTotallyAwesomeTest() throws Exception {
    assertTrue(true);
    //AppPreferences appPreferences = new AppPreferences(RuntimeEnvironment.application);
    //appPreferences.put("key", "test");
    //String test = appPreferences.getString("key");
    //assertThat(test, equalTo("test"));
  }
}
```

**Comment by KioKrofovitch** [comment]
Turns out, Robolectric has a difficult time accessing generated resource values.  At first I tried extending `RobolectricGradleTestRunner` class to add extra directories to the resource path, but this did not work. Ultimately, I had to create a shadow resource like this:
```
@Implements(Resources.class)
public class CustomShadowResource extends ShadowResources {
  @Override
  public CharSequence getText(int id) throws Resources.NotFoundException {
    if (id == R.string.tray__authority) return "com.example.tray";

    return super.getText(id);
  }
}
```

Then include this Shadow resource in my `TrayTest` class like this:
```@Config(constants = BuildConfig.class, sdk=21, shadows = CustomShadowResource.class)```

While I have resolved the missing string resource issue, the provider registration issue has returned:
```java.lang.IllegalStateException: could not access stored data with uri content://com.example.tray/internal_preferences/com.example/version?backup=true. Is the provider registered in the manifest of your application?```

**Comment by passsy** [comment]
I haven't had the time to look deeper into this. But I suggest to mock the `Storage` of `Tray`. Instead of  `TrayPreference` you should work with [`AbstractTrayPreference`](https://github.com/grandcentrix/tray/blob/806f53e1370709a33191b04a0b40ea86ca1d2eff/library/src/main/java/net/grandcentrix/tray/TrayPreferences.java#L43) and inject a `Storage` which doesn't require a `ContenteProvider`. You can use the [`MockTrayStorage`](https://github.com/grandcentrix/tray/blob/master/library/src/androidTest/java/net/grandcentrix/tray/mock/MockTrayStorage.java). Of cause this doesn't allow you to test multiprocess stuff.

I note that mocking tray for tests isn't as simple as it should. #futureimprovement

**Comment by vaibhavpali** [comment]
Could anyone here please help on below problem, I'm getting similar kind of issue:

 I have set up the roboelectric into my workspace, however I'm getting below error:

android.content.res.Resources$NotFoundException: unknown resource 2131231855
	at org.robolectric.shadows.ShadowAssetManager.getAndResolve(ShadowAssetManager.java:351)
	at org.robolectric.shadows.ShadowAssetManager.getResourceText(ShadowAssetManager.java:70)
	at android.content.res.AssetManager.getResourceText(AssetManager.java)
	at android.content.res.Resources.getText(Resources.java:270)
	at org.robolectric.shadows.ShadowResources.getText(ShadowResources.java:358)
	at android.content.res.Resources.getText(Resources.java)
	at android.content.res.Resources.getString(Resources.java:360)
	at org.robolectric.shadows.ShadowContext.getString(ShadowContext.java:33)
	at org.robolectric.shadows.ShadowContextWrapper.getString(ShadowContextWrapper.java:81)
	at android.content.Context.getString(Context.java)
	at com.example.wallet.WalletApplication.onCreate(WalletApplication.java:70)
	at org.robolectric.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:140)
	at org.robolectric.RobolectricTestRunner.setUpApplicationState(RobolectricTestRunner.java:433)
	at org.robolectric.RobolectricTestRunner$2.evaluate(RobolectricTestRunner.java:240)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:188)
	at org.robolectric.RobolectricTestRunner.runChild(RobolectricTestRunner.java:54)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.RobolectricTestRunner$1.evaluate(RobolectricTestRunner.java:152)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Android studio version: 2.3.3
Roboeletric version: 3.0

Test file code is: 

Inline image 1
![image](https://user-images.githubusercontent.com/15090114/29170618-2054280a-7df7-11e7-88d4-43bd0d12591b.png)

Inline image 2
![image](https://user-images.githubusercontent.com/15090114/29170626-29b68df2-7df7-11e7-9894-be61da0c1b07.png)

**Comment by nihk** [comment]
> ```
> @Implements(Resources.class)
> public class CustomShadowResource extends ShadowResources {
>   @Override
>   public CharSequence getText(int id) throws Resources.NotFoundException {
>     if (id == R.string.tray__authority) return "com.example.tray";
> 
>     return super.getText(id);
>   }
> }
> ```

I just tried this but it yields a compilation error: the class cannot resolve the override because there doesn't appear to be any `getText(int)` method in `ShadowResources`. I looked at the [robolectric source code](https://github.com/robolectric/robolectric/blob/1254df3c3bd10d0fa8d05d971d504aaf4442384e/shadows/framework/src/main/java/org/robolectric/shadows/ShadowResources.java) and don't see it there either. Am I missing something here? Maybe the API changed?
