### ISSUE TITLE
"could not access stored data with uri content" error

### ISSUE THREAD

**Issue by ElegantWang** [grandcentrix/tray#78]
My application is the only launcher of the android firmware.I got the follow error:
The `TrayPreferences` is initialized in `MyApplication.onCreate`
````
08-12 14:52:14.283 E/ActivityThread( 1462): Failed to find provider info for com.testtay.user_preference
08-12 14:52:14.293 E/CrashHandler( 1462): encountered a fatal error
08-12 14:52:14.293 E/CrashHandler( 1462): java.lang.RuntimeException: Unable to create application com.testtay.application.MyApplication: java.lang.IllegalStateException: could not access stored data with uri content://com.testtay.user_preference/internal_preferences/group/version?backup=true. Is the provider registered in the manifest of your application?
08-12 14:52:14.293 E/CrashHandler( 1462):       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4347)
08-12 14:52:14.293 E/CrashHandler( 1462):       at android.app.ActivityThread.access$1500(ActivityThread.java:135)
08-12 14:52:14.293 E/CrashHandler( 1462):       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
08-12 14:52:14.293 E/CrashHandler( 1462):       at android.os.Handler.dispatchMessage(Handler.java:102)
08-12 14:52:14.293 E/CrashHandler( 1462):       at android.os.Looper.loop(Looper.java:136)
08-12 14:52:14.293 E/CrashHandler( 1462):       at android.app.ActivityThread.main(ActivityThread.java:5017)
08-12 14:52:14.293 E/CrashHandler( 1462):       at java.lang.reflect.Method.invokeNative(Native Method)
08-12 14:52:14.293 E/CrashHandler( 1462):       at java.lang.reflect.Method.invoke(Method.java:515)
08-12 14:52:14.293 E/CrashHandler( 1462):       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
08-12 14:52:14.293 E/CrashHandler( 1462):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
08-12 14:52:14.293 E/CrashHandler( 1462):       at dalvik.system.NativeStart.main(Native Method)
08-12 14:52:14.293 E/CrashHandler( 1462): Caused by: java.lang.IllegalStateException: could not access stored data with uri content://com.testtay.user_preference/internal_preferences/group/version?backup=true. Is the provider registered in the manifest of your application?
08-12 14:52:14.293 E/CrashHandler( 1462):       at net.grandcentrix.tray.provider.TrayProviderHelper.queryProvider(TrayProviderHelper.java:145)
08-12 14:52:14.293 E/CrashHandler( 1462):       at net.grandcentrix.tray.provider.ContentProviderStorage.getVersion(ContentProviderStorage.java:214)
08-12 14:52:14.293 E/CrashHandler( 1462):       at net.grandcentrix.tray.core.Preferences.changeVersion(Preferences.java:224)
08-12 14:52:14.293 E/CrashHandler( 1462):       at net.grandcentrix.tray.core.Preferences.<init>(Preferences.java:51)
08-12 14:52:14.293 E/CrashHandler( 1462):       at net.grandcentrix.tray.core.AbstractTrayPreference.<init>(AbstractTrayPreference.java:31)
08-12 14:52:14.293 E/CrashHandler( 1462):       at net.grandcentrix.tray.TrayPreferences.<init>(TrayPreferences.java:43)
08-12 14:52:14.293 E/CrashHandler( 1462):       at net.grandcentrix.tray.TrayPreferences.<init>(TrayPreferences.java:48)
08-12 14:52:14.293 E/CrashHandler( 1462):       at com.testtay.common.preferences.CacheTrayPreferences.<init>(CacheTrayPreferences.java:24)
08-12 14:52:14.293 E/CrashHandler( 1462):       at com.testtay.common.preferences.UserPreferences.<init>(UserPreferences.java:34)
08-12 14:52:14.293 E/CrashHandler( 1462):       at com.testtay.common.preferences.UserPreferences.init(UserPreferences.java:21)
08-12 14:52:14.293 E/CrashHandler( 1462):       at com.testtay.utils.ProcessUtils.initCommon(ProcessUtils.java:149)
08-12 14:52:14.293 E/CrashHandler( 1462):       at com.testtay.application.process.MainProcessApp.create(MainProcessApp.java:64)
08-12 14:52:14.293 E/CrashHandler( 1462):       at com.testtay.application.MyApplication.onCreate(MyApplication.java:50)
08-12 14:52:14.293 E/CrashHandler( 1462):       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1021)
08-12 14:52:14.293 E/CrashHandler( 1462):       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
08-12 14:52:14.293 E/CrashHandler( 1462):       ... 10 more
````

**Comment by StefMa** [comment]
Can you please provide some more information?
How to setup tray and what's the code look like to initialized the TrayPreference?

**Comment by ElegantWang** [comment]
I wrapp tray in my helper class `UserPreferences` the setup code like this
````
    private TrayPreferences mUserPref;
    private static UserPreferences sInstance;
    private UserPreferences(Context context) {
        mUserPref = new TrayPreferences(context,"user",APP_PREF_VERSION);
    }

    public static void init(Context context) {
        if (sInstance == null) {
            sInstance = new UserPreferences(context);
        }
    }

    public static UserPreferences getInstance() {
        if (sInstance == null) {
            throw new IllegalStateException("Should init before use this class");
        }
        return sInstance;
    }
````
Then I initialize the `UserPreferences`  in `MyApplication#onCreate`
````
    UserPreferences.init(this);
````

### In addition I encounter this issue only one time and can't reproduce it.

**Comment by passsy** [comment]
I guess it's some kind of race condition where the `ContentProvider` isn't completely initialized when the `Application` gets created. There is nothing we can do.

I recommend not putting a `TrayPrefernces` into a singleton and initialize it in `Application#onCreate()`. Multiple instances of `TrayPreferences` are totally fine.

**Comment by ElegantWang** [comment]
Thanks for suggestion.
I will try to initialize `TrayPreferences` when I use it first time not in `Application#onCreate()` to avoid the race condition between the **`ContentProvider`** and **`Launcher`** which is my app here.
