### ISSUE TITLE
Found a crash about the sqlite

### ISSUE THREAD

**Issue by panyiho** [grandcentrix/tray#86]
JNI: CheckJNI is off; workarounds are off; pins=0; globals=269
DALVIK THREADS:
(mutexes: tll=0 tsl=0 tscl=0 ghl=0)
"main" prio=5 tid=1 NATIVE
  | group="main" sCount=1 dsCount=0 obj=0x41db7d08 self=0x415cd008
  | sysTid=10032 nice=-11 sched=0/0 cgrp=apps handle=1074487636
  | state=D schedstat=( 0 0 0 ) utm=88 stm=33 core=0
  #00  pc  0002035c  pwrite64 LINE:libc.so
  #01  pc  0000c3b7  /system/lib/libsqlite.so
  #02  pc  0001ccb5  /system/lib/libsqlite.so
  #03  pc  000312bb  /system/lib/libsqlite.so
  #04  pc  00035ecd  /system/lib/libsqlite.so
  #05  pc  0003608f  /system/lib/libsqlite.so
  #06  pc  00036b51  /system/lib/libsqlite.so
  #07  pc  000537cb  /system/lib/libsqlite.so
  #08  pc  000417f3  sqlite3_step LINE:libsqlite.so
  #09  pc  0006492d  /system/lib/libandroid_runtime.so
  #10  pc  00064989  /system/lib/libandroid_runtime.so
  #11  pc  0001dd4c  dvmPlatformInvoke LINE:libdvm.so
  #12  pc  0004dfc7  /system/lib/libdvm.so
  #13  pc  00027160  /system/lib/libdvm.so
  #14  pc  0002e0a8  dvmMterpStd LINE:libdvm.so
  #15  pc  0002b754  /system/lib/libdvm.so
  #16  pc  000603bb  /system/lib/libdvm.so
  #17  pc  000603df  /system/lib/libdvm.so
  #18  pc  0006b999  dvmInitClass LINE:libdvm.so
  #19  pc  0006c469  dvmResolveStaticField LINE:libdvm.so
  #20  pc  00022574  dvmAsmSisterStart LINE:libdvm.so
  #21  pc  0002e0a8  dvmMterpStd LINE:libdvm.so
  #22  pc  0002b754  /system/lib/libdvm.so
  #23  pc  0006069d  /system/lib/libdvm.so
  #24  pc  000685b3  /system/lib/libdvm.so
  #25  pc  00027160  /system/lib/libdvm.so
  #26  pc  0002e0a8  dvmMterpStd LINE:libdvm.so
  #27  pc  0002b754  /system/lib/libdvm.so
  #28  pc  000603bb  /system/lib/libdvm.so
  #29  pc  00049c17  /system/lib/libdvm.so
  #30  pc  00051a37  /system/lib/libandroid_runtime.so
  #31  pc  00052fcb  /system/lib/libandroid_runtime.so
  at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
  at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:972)
  at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
  at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
  at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1603)
  at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1473)
  at com.tray.provider.SqliteHelper.insertOrUpdate(ProGuard:148)
  at com.tray.provider.TrayContentProvider.insertOrUpdate(ProGuard:1206)
                                           insert
  at android.content.ContentProvider$Transport.insert(ContentProvider.java:220)
  at android.content.ContentResolver.insert(ContentResolver.java:1195)
  at com.tray.provider.TrayProviderHelper.persist(ProGuard:149)
  at com.tray.provider.ContentProviderStorage.com.tray.provider.TrayProviderHelper.persist(ProGuard:13140)
                                              setVersion
  at com.tray.core.Preferences.changeVersion(ProGuard:270)
  at com.tray.core.Preferences.isVersionChangeChecked(ProGuard:290)
  at com.tray.core.Preferences.<init>(ProGuard:56)
  at com.tray.core.AbstractTrayPreference.<init>(ProGuard:32)
  at com.tray.TrayPreferences.<init>(ProGuard:42)
  at com.tray.TrayPreferences.<init>(ProGuard:47)

**Comment by panyiho** [comment]
We found a crash about sqlite,is a little troublesome

**Comment by passsy** [comment]
Please provide more information.
Which tray version are you using? What was the device this is happening and which Android version?

**Comment by yunair** [comment]
Is there any problem calling `new AppPreference()` in `Application#onCreate()`??

**Comment by passsy** [comment]
I have in mind that I've seen crashes there because the `ContentProvider` isn't ready yet or the `Application` is too busy on slow phones causing such problems.

But without more information from your side I can't help you.

**Comment by zrzhong** [comment]
I got this problem too.I found this message in traces.txt.
`"main" prio=5 tid=1 NATIVE
  | group="main" sCount=1 dsCount=0 obj=0x41601400 self=0x415394b8
  | sysTid=4780 nice=0 sched=0/0 cgrp=apps handle=1074598228
  | state=D schedstat=( 20041969115 428330280 3159 ) utm=1890 stm=114 core=0
  #00  pc 00020788  /system/lib/libc.so (fdatasync+12)
  #01  pc 00017317  /system/lib/libsqlite.so
  #02  pc 00004a17  /system/lib/libsqlite.so
  #03  pc 0002abb9  /system/lib/libsqlite.so
  #04  pc 0002af49  /system/lib/libsqlite.so
  #05  pc 0002b111  /system/lib/libsqlite.so
  #06  pc 0002b761  /system/lib/libsqlite.so
  #07  pc 0003d157  /system/lib/libsqlite.so
  #08  pc 00033779  /system/lib/libsqlite.so (sqlite3_step+1316)
  #09  pc 0005fb89  /system/lib/libandroid_runtime.so
  #10  pc 0005fbe5  /system/lib/libandroid_runtime.so
  #11  pc 0001db4c  /system/lib/libdvm.so (dvmPlatformInvoke+112)
  #12  pc 0004e003  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
  #13  pc 00026f60  /system/lib/libdvm.so
  #14  pc 0002deec  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
  #15  pc 0002b598  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
  #16  pc 00060711  /system/lib/libdvm.so (dvmInvokeMethod(Object*, Method const*, ArrayObject*, ArrayObject*, ClassObject*, bool)+392)
  #17  pc 00068743  /system/lib/libdvm.so
  #18  pc 00026f60  /system/lib/libdvm.so
  #19  pc 0002deec  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
  #20  pc 0002b598  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
  #21  pc 0006042f  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+338)
  #22  pc 00049beb  /system/lib/libdvm.so
  #23  pc 0004d52f  /system/lib/libandroid_runtime.so
  #24  pc 0004e253  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, char const*)+354)
  #25  pc 0000105b  /system/bin/app_process
  #26  pc 0000e3eb  /system/lib/libc.so (__libc_init+50)
  #27  pc 00000d7c  /system/bin/app_process
  at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
  at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
  at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
  at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
  at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
  at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
  at net.grandcentrix.tray.provider.SqliteHelper.insertOrUpdate(SqliteHelper.java:148)
  at net.grandcentrix.tray.provider.TrayContentProvider.insertOrUpdate(TrayContentProvider.java:200)
  at net.grandcentrix.tray.provider.TrayContentProvider.insert(TrayContentProvider.java:179)
  at android.content.ContentProvider$Transport.insert(ContentProvider.java:220)
  at android.content.ContentResolver.insert(ContentResolver.java:1190)
  at net.grandcentrix.tray.provider.TrayProviderHelper.persist(TrayProviderHelper.java:128)
  at net.grandcentrix.tray.provider.ContentProviderStorage.put(ContentProviderStorage.java:257)
  at net.grandcentrix.tray.provider.ContentProviderStorage.put(ContentProviderStorage.java:229)
  at net.grandcentrix.tray.core.Preferences.put(Preferences.java:117)
  at com.commen.utils.PreferencesLoader.setObject(PreferencesLoader.java:47)
  at com.commen.utils.MyPreferensLoader.setForwardRevertMap(MyPreferensLoader.java:192)
  at com.liefeng.singleusb.usbhostdemo.USBSever.assemblyCmd(USBSever.java:651)
  at com.liefeng.singleusb.usbhostdemo.USBSever.initDevices(USBSever.java:522)
  at com.liefeng.singleusb.usbhostdemo.USBSever.access$100(USBSever.java:114)
  at com.liefeng.singleusb.usbhostdemo.USBSever$2.onNext(USBSever.java:392)
  at com.liefeng.singleusb.usbhostdemo.USBSever$2.onNext(USBSever.java:376)
  at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:139)
  at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:207)
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
  at android.os.Handler.handleCallback(Handler.java:733)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5001)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:815)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:631)
  at dalvik.system.NativeStart.main(Native Method)`
