### ISSUE TITLE
error ClassNotFoundException on GALAXY S3

### ISSUE THREAD

**Issue by find-happiness** [grandcentrix/tray#95]
FATAL EXCEPTION: main
                                                 java.lang.RuntimeException: Unable to get provider net.grandcentrix.tray.provider.TrayContentProvider: java.lang.ClassNotFoundException: Didn't find class "net.grandcentrix.tray.provider.TrayContentProvider" on path: /data/app/com.yudong.fitnew-1.apk
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5157)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4755)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4693)
                                                     at android.app.ActivityThread.access$1400(ActivityThread.java:160)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:176)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5454)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:525)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "net.grandcentrix.tray.provider.TrayContentProvider" on path: /data/app/com.yudong.fitnew-1.apk
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:64)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:5142)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4755) 
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4693) 
                                                     at android.app.ActivityThread.access$1400(ActivityThread.java:160) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1377) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:176) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5454) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:525) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025) 
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by StefMa** [comment]
Thank you for your Stacktrace.
But without **any** information (how do you setup tray etc.) we are unable to help...
Maybe you have reached the DexCount limit?

**Comment by StefMa** [comment]
Closed because of no response from the client.
If you have still the issue and can provide more information feel free to comment here again...
@find-happiness
